// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcBnFy05GiNtce4yWc9llTYOtBloTfzfY',
    appId: '1:932368924378:web:67871f8f0182068dfbafe3',
    messagingSenderId: '932368924378',
    projectId: 'fimos-18d64',
    authDomain: 'fimos-18d64.firebaseapp.com',
    storageBucket: 'fimos-18d64.appspot.com',
    measurementId: 'G-WHK22H6325',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaehjD7RpMjg4lc-4f12MCiEuVsCuNvlQ',
    appId: '1:932368924378:android:8515144521eadb04fbafe3',
    messagingSenderId: '932368924378',
    projectId: 'fimos-18d64',
    storageBucket: 'fimos-18d64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwA68j2Z7CWOKE7syVQpflnR45eLpG0xE',
    appId: '1:932368924378:ios:a373edba13592dcefbafe3',
    messagingSenderId: '932368924378',
    projectId: 'fimos-18d64',
    storageBucket: 'fimos-18d64.appspot.com',
    iosClientId: '932368924378-odksdktlqefl26h888jb7cghdnlesnk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fimosFix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwA68j2Z7CWOKE7syVQpflnR45eLpG0xE',
    appId: '1:932368924378:ios:a373edba13592dcefbafe3',
    messagingSenderId: '932368924378',
    projectId: 'fimos-18d64',
    storageBucket: 'fimos-18d64.appspot.com',
    iosClientId: '932368924378-odksdktlqefl26h888jb7cghdnlesnk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fimosFix',
  );
}
